### ISSUE TITLE
Build out /polls endpoint

### ISSUE THREAD

**Issue by jcaip** [JeffreyQ/UCLA-CS-130#3]
This should let us get all the polls that a user is associated with (either created or subscribed to)

- [ ] endpoint: GET /polls

get all polls that you're subscribed to. 
Query poll-user relationship table for all relationships where user_id = <user> and then join on polls table

- [ ] endpoint: GET /polls/me

get all the polls that you've created.
query polls table with a filter where creator_id = <user>

**Comment by lawrencechen98** [comment]
Changed endpoints to:
GET /polls
Retrieves polls that you have created, to be parallel in resource usage such that
POST /polls creates your own polls

Instead
GET /polls/following
Retrieves polls that the user is following i.e. subscribed to
