### ISSUE TITLE
/polls poll specific endpoints 

### ISSUE THREAD

**Issue by jcaip** [JeffreyQ/UCLA-CS-130#6]
This should let us manipulate a single poll. 

- [ ] endpoint: GET /polls/<id>

get poll details  + responses 
query poll table for poll, then join on responses table to provide poll + all responses

- [x] endpoint: PATCH /polls/<id>

lets you close a poll by changing the is_closed field. Should be similar to below 

- [x] endpoint: POST /polls

add a new poll to the db - take in passed in poll details and add to polls table.

**Comment by lawrencechen98** [comment]
endpoint for getting responses should be
GET /polls/response/<poll_id> (or maybe /polls/<poll_id>/response ? )
while we create a response with 
POST /polls/response

That way the endpoints are parallel, and also the GET /poll endpoint is already used for retrieving lists of polls that you have created in general
